"""empty message

Revision ID: 16fffe9dc5a1
Revises: ee3eda32ee5d
Create Date: 2022-02-22 07:59:14.208852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fffe9dc5a1'
down_revision = '484fa21ca6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
