"""empty message

Revision ID: 25fa6f8c06ab
Revises: 16fffe9dc5a1
Create Date: 2022-02-22 08:17:57.666081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fa6f8c06ab'
down_revision = '16fffe9dc5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'frequency',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contact', 'first',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=40), nullable=False),
    sa.Column('due_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
