"""role updates

Revision ID: 408fe8a78b20
Revises: 3cabfe34e355
Create Date: 2022-02-27 08:44:35.096346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "408fe8a78b20"
down_revision = "3cabfe34e355"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("default", sa.Boolean(), nullable=True))
    op.add_column("roles", sa.Column("permissions", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_roles_default"), "roles", ["default"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roles_default"), table_name="roles")
    op.drop_column("roles", "permissions")
    op.drop_column("roles", "default")
    # ### end Alembic commands ###
