"""empty message

Revision ID: ee3eda32ee5d
Revises: 
Create Date: 2022-02-21 15:31:21.706920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3eda32ee5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_email', table_name='contact')
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.create_index('ix_contact_email', 'contact', ['email'], unique=False)
    # ### end Alembic commands ###
